spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_networks
    username: book-network
    password: yt1234
    driver-class-name: org.postgresql.Driver
  jpa:

    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: akl
    password: akl
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key:  dGhpcy1pcy1hLXNlY3VyZS1yYW5kb20tc2VjcmV0LWtleQ==
      expiration:  8640000
    mailing:
      frontend:
        activation-url: https://localhost:4200/activate_account
        file:
          upload:
            photos-output-path:  ./uploads
server:
  port: 8088

